---
name: App Tests
description: Run Go integration tests for an app

inputs:
  app:
    description: App Name
    required: true
  image:
    description: Image to test
    required: true
  token:
    description: GitHub Token
    required: true

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
      with:
        go-version-file: go.mod

    - name: Run Tests
      shell: bash
      env:
        APP: ${{ inputs.app }}
        TEST_IMAGE: ${{ inputs.image }}
      run: |-
        go test -v ./apps/${APP}/...
