---
name: App Tests
description: Run Go integration tests for an app

inputs:
  app:
    description: App Name
    required: true
  image:
    description: Image to test
    required: true
  token:
    description: GitHub Token
    required: true

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: go.mod

    - name: Run Tests
      shell: bash
      env:
        APP: ${{ inputs.app }}
        TEST_IMAGE: ${{ inputs.image }}
      run: |-
        go test -v ./apps/${APP}/...
