---
name: App Exists
description: Check if an app exists in the container registry

inputs:
  app:
    description: App Name
    required: true

outputs:
  exists:
    description: App Exists
    value: ${{ steps.app.outputs.exists }}

runs:
  using: composite
  steps:
    - name: App Exists
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      id: app
      env:
        APP: ${{ inputs.app }}
      with:
        script: |-
          const app = process.env.APP;
          let pkg;
          try {
              const { data } = await github.rest.packages.getPackageForUser({
                  package_type: 'container',
                  package_name: app,
                  username: context.repo.owner,
              });
              pkg = data;
          } catch (error) {
              if (error.status !== 404) throw error;
          }
          core.setOutput('exists', typeof pkg !== "undefined");
